export const REVIEW_REQUESTED = 'review_requested'
export const SYNCHRONIZE = 'synchronize'
export const COMMENT_CRETED = 'created'
export const COMMENT_EDITED = 'edited'
export const MASTER_BRANCH = 'refs/heads/master'
export const DEVELOP_BRANCH = 'refs/heads/develop'