export const REVIEW_REQUESTED = 'review_requested'
export const SYNCHRONIZE = 'synchronize'
export const COMMENT_CRETED = 'created'
export const COMMENT_EDITED = 'edited'
export const PULL_REQUEST_MERGED = 'merged'
export const MASTER_BRANCH = 'refs/heads/master'