name: "Pull Request to Slack"
description: "Pull request reviewer will be mentioned on slack channel"
branding:
  icon: "bell"
  color: "orange"
inputs:
  github-token: # id of input
    description: "github-token"
    required: true
    # default: "World"
  slack-webhook-url:
    required: true
  github-run-id:
    required: true
  user-data:
    required: true
  staging-webhook-url:
    required: true
outputs:
  result: # id of output
    description: "result"
runs:
  using: "node12"
  main: "dist/index.js"
